KS-3-4 lesson_3_task_4
Emil-Emekmynenko/Kotlin_Sprint pull request #14
Opened 2024-01-20 20:05 UTC by Emil-Emekmynenko

2024-01-21 07:06 UTC, ievetrovdev requested changes

2024-01-21 07:06 UTC, ievetrovdev commented on src/main/kotlin/lesson3/lesson_3_task_4.kt
> +    var numberMove = "1"
ходы удобнее сделать строкой, тогда подсчет будет удобнее, не придется каждый раз самому писать ход, а только добавлять единицу

2024-01-21 09:36 UTC, Emil-Emekmynenko commented on src/main/kotlin/lesson3/lesson_3_task_4.kt
> +    var numberMove = "1"
вроде бы так и сделал в выводе в консоль, чтобы в переменной только подставлять цифру

2024-01-22 07:43 UTC, ievetrovdev requested changes

2024-01-22 07:43 UTC, ievetrovdev commented on src/main/kotlin/lesson3/lesson_3_task_4.kt
> +    var numberMove = "1"
Извини, Опечатался. Сделать int. тогда на каждый новый ход будет достаточно добавить единицу

2024-01-24 07:25 UTC, ievetrovdev approved these changes
Отлично

2024-01-24 17:50 UTC, merged