KS-1-2 lesson_1_task_2
Emil-Emekmynenko/Kotlin_Sprint pull request #2
Opened 2024-01-17 20:20 UTC by Emil-Emekmynenko

2024-01-18 05:04 UTC, ievetrovdev requested changes

2024-01-18 05:04 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson_1_task_2.kt
> +//    println(numberOfWorkers)
В Idea есть автоформатирование кода: Находясь в файле Ctrl+Alt+L (для windows) или ⌥+⌘+L (для osx)

2024-01-18 07:47 UTC, Emil-Emekmynenko commented on src/main/kotlin/lesson1/lesson_1_task_2.kt
> +//    println(numberOfWorkers)
Получается не правильно стояла фигурная скобка рядом с функцией?
Комбинация форматирования выдала только эту ошибку)

2024-01-19 02:05 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson_1_task_2.kt
> +//    println(numberOfWorkers)
да, еще у комментария как будто не было отступа слева, но это видимо гит так показывает)

2024-01-19 02:05 UTC, ievetrovdev approved these changes

2024-01-19 07:29 UTC, merged