KS-1-5 lesson_1_task_5
Emil-Emekmynenko/Kotlin_Sprint pull request #5
Opened 2024-01-17 20:34 UTC by Emil-Emekmynenko

2024-01-18 05:07 UTC, ievetrovdev requested changes

2024-01-18 05:07 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    val minutesOfSpace = seconds / 60
Чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-01-18 10:07 UTC, Emil-Emekmynenko commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    val minutesOfSpace = seconds / 60
Спасибо за развёрнутый ответ)

2024-01-19 02:11 UTC, ievetrovdev requested changes

2024-01-19 02:11 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    val constTime = 60
стиль констант отличен от обычных переменных. В [документации по ссылке](https://developer.android.com/kotlin/style-guide#constant_names) есть более полное описание стайл гайда. и константы нужно выносить за область видимости функции)

2024-01-19 02:13 UTC, ievetrovdev requested changes

2024-01-19 02:13 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson_1_task_5.kt
> +    println("0$hoursOfSpace:$remainMinutesOfHours:0$remainSecondsOfMinutes")
попробуй для вывода использовать `String.format`, он может принимать различные аргументы и это позволит избавиться от подставления нуля в строку)

2024-01-20 06:08 UTC, ievetrovdev approved these changes

2024-01-20 15:19 UTC, merged