KS-2-4 lesson_2_task_4
Emil-Emekmynenko/Kotlin_Sprint pull request #9
Opened 2024-01-19 16:01 UTC by Emil-Emekmynenko

2024-01-19 16:28 UTC, ievetrovdev requested changes
Есть нарушения в git флоу, то есть в логике работы с коммитами и ветками.
Обрати внимание, сначала ты сделал одну задачу, запушил и все ок.
Затем ты закоммитил в эту же ветку другую задачу задачу (либо создал следующую ветку из предыдущей рабочей ветки) – это видно в истории коммитов.

Что из этого следует? В пулл реквест с одной задачей попала задача, которая должна быть в другой ветке. Это нарушает суть разделения кода задач по веткам. Задача из одной ветки не должна знать и пересекаться с задачей из другой ветки.

На большом проекте затрагивается много файлов и если в одном ПР делать другие изменения (из другой задачи), то при слиянии может быть много проблем и/или гит конфликтов. Например, над кодом другой задачи уже работает программист, изменения из второй задачи не проверены и не протестированы (тестировщики проверяют функционал по конкретному тех. заданию в рамках данного описания задачи в конкретной ветке).

Новые ветки создаем только из мастера (который предварительно надо обновить, если до этого мержились задачи в гитхабе), чтобы не было пересечений с другими тасками)

Что делать?
в данном пулл реквесте надо:
- переключиться в ветку текущего ПР
- удалить лишний файл с задачей (физически из проекта)
- сделать коммит (с изменением удаления)
- прислать ссылку на этот же пулл реквест снова в бот

И новые ветки всегда создаем из основной ветки master.

2024-01-19 16:28 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson_2_task_4.kt
> +    val buff = 0.2
В ТЗ фигурирует значение 20 (процентов). Его также надо проинициализировать и только потом производить арифметические операции. Это позволит сделать более гибким и легко изменяемым, если понадобится изменить характеристики.

2024-01-19 17:08 UTC, Emil-Emekmynenko commented on src/main/kotlin/lesson2/lesson_2_task_4.kt
> +    val buff = 0.2
А как понять, что будет конфликт между ветками?
Как это избежать?Или просто со временем придёт, что всегда идёшь в мастер за новой веткой)

2024-01-19 17:20 UTC, Emil-Emekmynenko commented
Похоже я не разобрался, я удалил лишнюю задачу из ветки и снова её запушил, но ветка так и подсвечивается с красным крестиком

<img width="1335" alt="Снимок экрана 2024-01-19 в 20 17 55" src="https://github.com/Emil-Emekmynenko/Kotlin_Sprint/assets/104070881/90f6cc8b-cbea-4c86-9ae5-bb227f1d3a25">

2024-01-20 15:01 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson_2_task_4.kt
> +    val buff = 0.2
> А как понять, что будет конфликт между ветками? Как это избежать?Или просто со временем придёт, что всегда идёшь в мастер за новой веткой)

ответил в лс)

2024-01-20 15:09 UTC, ievetrovdev approved these changes
Отписал детали в ЛС, по таске все ок!

2024-01-20 15:28 UTC, merged